name: project_reunite
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  
  appwrite: ^9.0.1
  cloud_firestore: ^4.8.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  flutter_webrtc: ^0.9.34
  freerasp: ^6.0.0
  get_it: ^7.3.0
  google_fonts: ^5.0.0
  share_plus: ^7.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  msix: ^3.16.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/SVG